### ISSUE TITLE
Dataset and fine-tune process

### ISSUE THREAD

**Issue by SYL-322** [MehmetAygun/saor#1]
Hi Mehmet,

Thanks for your excellent work!
I would like to ask if you have any plans to publish your collected SAOR-101 dataset and the fine-tuning process for the different categories?

Best!

**Comment by MehmetAygun** [comment]
Hi Mofafa,

Thanks for your interest in our work, after I resolve some copyright issues (hopefully soon) related to some images in the dataset I will release processed images and how to do finetuning. 

Best
Mehmet

**Comment by SYL-322** [comment]
Thank you!
